modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="danknull" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dank Null" #mandatory
logoFile="examplemod.png" #optional
credits="Forge, Original Author: " #optional
authors="Inteloperator, Jay-Heltrato," #optional
description='''
Port to 1.19.2 dank null.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.forge]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.21,)"
    ordering="NONE"
    side="BOTH"